from app.database import SessionLocal
from app.models.challenge import Challenge, ChallengeCategory, ChallengeDifficulty
import uuid

db = SessionLocal()

# Sample challenges
challenges = [
    {
        "id": uuid.uuid4(),
        "title": "Explain the Decorator Pattern",
        "category": ChallengeCategory.COMPREHENSION,
        "difficulty": ChallengeDifficulty.MEDIUM,
        "description": "Analyze this Python decorator and explain what it does, when you'd use it, and any potential issues.",
        "code_snippet": """def memoize(func):
    cache = {}
    def wrapper(*args):
        if args not in cache:
            cache[args] = func(*args)
        return cache[args]
    return wrapper

@memoize
def fibonacci(n):
    if n < 2:
        return n
    return fibonacci(n-1) + fibonacci(n-2)""",
        "language": "python",
        "time_limit": 15,
        "points": 50,
        "is_active": True
    },
    {
        "id": uuid.uuid4(),
        "title": "Fix the Memory Leak",
        "category": ChallengeCategory.DEBUGGING,
        "difficulty": ChallengeDifficulty.HARD,
        "description": "This event listener implementation has a memory leak. Find it and explain how to fix it.",
        "code_snippet": """class EventEmitter:
    def __init__(self):
        self.listeners = []
    
    def on(self, event, callback):
        self.listeners.append(callback)
    
    def emit(self, event):
        for callback in self.listeners:
            callback()
    
    def off(self, event, callback):
        # Remove callback
        pass

# Usage
emitter = EventEmitter()
for i in range(1000):
    emitter.on('data', lambda: print(f'Event {i}'))""",
        "language": "python",
        "time_limit": 20,
        "points": 75,
        "is_active": True
    },
    {
        "id": uuid.uuid4(),
        "title": "Identify SQL Injection",
        "category": ChallengeCategory.SECURITY,
        "difficulty": ChallengeDifficulty.EASY,
        "description": "Review this code for security vulnerabilities and suggest fixes.",
        "code_snippet": """@app.route('/user/<user_id>')
def get_user(user_id):
    query = f"SELECT * FROM users WHERE id = {user_id}"
    result = db.execute(query)
    return jsonify(result)

@app.route('/search')
def search():
    term = request.args.get('q')
    query = f"SELECT * FROM products WHERE name LIKE '%{term}%'"
    results = db.execute(query)
    return jsonify(results)""",
        "language": "python",
        "time_limit": 10,
        "points": 40,
        "is_active": True
    },
    {
        "id": uuid.uuid4(),
        "title": "Debug the Async Function",
        "category": ChallengeCategory.DEBUGGING,
        "difficulty": ChallengeDifficulty.MEDIUM,
        "description": "This async function has a bug that causes race conditions. Find and fix it.",
        "code_snippet": """async def process_data(items):
    results = []
    for item in items:
        result = await fetch_data(item)
        results.append(result)
    return results

async def fetch_data(item):
    await asyncio.sleep(1)
    return item * 2

# The code takes too long for large lists
# How can you make it faster?""",
        "language": "python",
        "time_limit": 15,
        "points": 60,
        "is_active": True
    },
    {
        "id": uuid.uuid4(),
        "title": "Explain the Closure",
        "category": ChallengeCategory.COMPREHENSION,
        "difficulty": ChallengeDifficulty.EASY,
        "description": "Explain what this JavaScript code does and what will be logged to the console.",
        "code_snippet": """function createCounter() {
    let count = 0;
    return {
        increment: () => ++count,
        decrement: () => --count,
        getCount: () => count
    };
}

const counter1 = createCounter();
const counter2 = createCounter();

counter1.increment();
counter1.increment();
counter2.increment();

console.log(counter1.getCount());
console.log(counter2.getCount());""",
        "language": "javascript",
        "time_limit": 10,
        "points": 30,
        "is_active": True
    },
    {
        "id": uuid.uuid4(),
        "title": "Review AI-Generated Authentication",
        "category": ChallengeCategory.AI_REVIEW,
        "difficulty": ChallengeDifficulty.MEDIUM,
        "description": "This authentication code was generated by AI. Identify security issues and suggest improvements.",
        "code_snippet": """def login(username, password):
    user = db.query(f"SELECT * FROM users WHERE username='{username}'")
    if user and user.password == password:
        session['user_id'] = user.id
        session['is_admin'] = user.is_admin
        return True
    return False

def check_auth():
    if 'user_id' in session:
        return True
    return False

@app.route('/admin')
def admin_panel():
    if session.get('is_admin'):
        return render_template('admin.html')
    return 'Not authorized'""",
        "language": "python",
        "time_limit": 15,
        "points": 55,
        "is_active": True
    }
]

# Insert challenges
for challenge_data in challenges:
    challenge = Challenge(**challenge_data)
    db.add(challenge)

db.commit()
print(f"✅ Added {len(challenges)} sample challenges!")
db.close()